blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_development/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=255, db_index=True, null=True, blank=True, verbose_name="URL")
    body = models.TextField(verbose_name='содержимое')
    image_preview = models.ImageField(upload_to='material/', verbose_name='изображение', null=True, blank=True)
    data_create = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_public = models.BooleanField(verbose_name='признак публикации', default=True)
    count_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from blog.models import Blog


class ModeratorBlogForm:
    class Meta:
        model = Blog
        fields = ('title', 'body', 'data_create', 'count_views',)

blog/views.py
from django.contrib.auth.mixins import AccessMixin
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)

from blog.models import Blog


class ContentManagerRequiredMixin(AccessMixin):
    """Verify that the current user is content manager."""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if not request.user.is_content_manager():
            raise Http404
        return super().dispatch(request, *args, **kwargs)


class BlogCreateView(ContentManagerRequiredMixin, CreateView):
    model = Blog
    permission_required = "main.add_blog"
    fields = ("title", "body", "is_public")
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(ContentManagerRequiredMixin, UpdateView):
    model = Blog
    fields = ("title", "body", "is_public")
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:view", args=[self.kwargs.get("pk")])


class BlogListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_public=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogDeleteView(ContentManagerRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:list")

blog/templates/blog/blog_confirm_delete.html
 {% extends 'main/base.html'%}
{% load my_tags %}
 {% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить материал "{{ object.title}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
 {% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="card-header">
        <h3 class="card-title">
            Материал "{{ object.title }}" ({{ object.slug }})
        </h3>
        <img src="{{ object.image_preview }}" />
    </div>
    <div class="card-body">
        <p>
            {{ object.body }}
        </p>
    </div>
    <div class="card-footer">
        Просмотры: {{ object.count_views }}
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
 {% extends 'main/base.html'%}
{% load my_tags %}
 {% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 {% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить блог</a>
    </div>
    {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img src="{{ object.image_preview|my_media }}" class="card-img-top" alt="blog image">
                <div class="card-body">
                    <p class="card-text">
                        {{object|title}}
                    </p>
                    <div class="d-flex justify-context-between alight-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:view' object.pk %}"
                               class="btn btn-sm btn-outline-secondary">View</a>
                            <a href="{% url 'blog:update' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Update</a>
                            <a href="{% url 'blog:delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}