blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_development/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    LoginView,
    LogoutView,
    RegisterView,
    VerificationFailedView,
    UserUpdateView,
    generate_new_password,
    VerifyEmailView,
    toggle_active,
    UserListView,
)

app_name = UsersConfig.name


urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile", UserUpdateView.as_view(), name="profile"),
    path("profile/genpassword/", generate_new_password, name="generate_new_password"),
    path("users/", UserListView.as_view(), name="users"),
    path("toggle_active/<int:pk>/", toggle_active, name="toggle_active"),
    path(
        "verify-email/<str:uidb64>/<str:token>/",
        VerifyEmailView.as_view(),
        name="verify_email",
    ),
    path(
        "verification_failed/",
        VerificationFailedView.as_view(),
        name="verification_failed",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name="Email")
    full_name = models.CharField(max_length=255, verbose_name="Full Name")
    email_verified = models.BooleanField(default=False)
    email_verification_token = models.CharField(max_length=100, null=True, blank=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def is_content_manager(self):
        return self.groups.filter(name="Content Manager").exists()

    def is_moderator(self):
        return self.groups.filter(name="Moderator").exists()

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("set_user_deactivate", "Can deactivate user"),
            ("view_all_users", "Can view all users"),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'full_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from users.forms import UserForm, UserRegisterForm
from users.models import User


# Create your views here.
class LoginView(BaseLoginView):
    template_name = "users/login.html"


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")
    template_name = "users/register.html"

    def form_valid(self, form):
        new_user = form.save(commit=False)
        new_user.is_active = False
        new_user.save()
        token = default_token_generator.make_token(new_user)
        new_user.email_verification_token = token
        new_user.save()
        uid = urlsafe_base64_encode(force_str(new_user.pk).encode())
        verification_url = reverse("users:verify_email", kwargs={"uidb64": uid, "token": token})
        verification_url = self.request.build_absolute_uri(verification_url)
        send_mail(
            subject="Подтверждение электронной почты",
            message=render_to_string("users/verify_email.txt", {"verification_url": verification_url}),
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email],
            fail_silently=False,
        )
        return super().form_valid(form)


@login_required
def generate_new_password(request):
    new_password = "".join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject="Смена пароля",
        message=f"Ваш новый пароль:{new_password}",
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
        fail_silently=False,
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse("main:index"))


@permission_required("users.set_user_deactivate")
def toggle_active(request, pk):
    """Пермиссия: функция для активации/деактивации пользователя"""
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse("users:users"))


class VerifyEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user and user.email_verification_token == token:
            user.email_verified = True
            user.is_active = True
            user.save()
            return redirect("users:login")
        else:
            # Обработка ошибки подтверждения
            return redirect("users:verification_failed")


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy("users:profile")
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


class VerificationFailedView(TemplateView):
    template_name = "users/verification_failed.html"


class UserListView(PermissionRequiredMixin, ListView):
    """Класс для просмотра списка пользователей"""

    permission_required = "users.view_all_users"
    model = User

    def get_queryset(self):
        return super().get_queryset().exclude(pk=self.request.user.pk).exclude(is_superuser=True)

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Профиль
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header mx-auto text-center">
    <h2 class="display-4">Список пользователей</h2>
    <p class="lead">Блокировка пользователей</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-3 box-shadow">
                {% if object.is_active %}
                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">{{object.email}}</h1>
                </div>
                    <a href="{% url 'users:toggle_active' object.pk %}" type="button"
                       class="btn btn-lg btn-block btn-outline-primary">Деактивировать пользователя</a>
                {% else %}
                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">{{object.email}}</h1>
                </div>
                    <a href="{% url 'users:toggle_active' object.pk %}" type="button"
                       class="btn btn-lg btn-block btn-outline-success">Aктивировать пользователя</a>
                </div>
            {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/verification_failed.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                Ошибка регистрации
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}