blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import (
    NewsLetterListView,
    NewsLetterCreateView,
    NewsLetterDetailView,
    NewsLetterUpdateView,
    ClientCreateView,
    MessageCreateView,
    NewsLetterDeleteView,
    MyNewsLetterListView,
)

app_name = MainConfig.name

urlpatterns = [
    path("", cache_page(5)(NewsLetterListView.as_view()), name="index"),
    path("create/", NewsLetterCreateView.as_view(), name="newsletter_create"),
    path("message/<int:pk>/create", MessageCreateView.as_view(), name="message_create"),
    path("newsletter/<int:pk>/delete", NewsLetterDeleteView.as_view(), name="newsletter_delete"),
    path("newsletter/<int:pk>", NewsLetterDetailView.as_view(), name="newsletter_detail"),
    path("my_newsletter/", MyNewsLetterListView.as_view(), name="my_newsletter_list"),
    path("newsletter/<int:pk>/update", NewsLetterUpdateView.as_view(), name="newsletter_update"),
    path("subscribe/<int:pk>", ClientCreateView.as_view(), name="client_create"),
]

service_development/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.conf import settings
from django.db import models


class StatusChoice(models.IntegerChoices):
    CREATED = 1, "Создана"
    PROCESSING = 2, "В обработке"
    COMPLETED = 3, "Завершена"
    ERROR = 4, "Ошибка"


class PeriodicityChoice(models.IntegerChoices):
    EVERY_DAY = 1, "Каждый день"
    EVERY_WEEK = 2, "Каждую неделю"
    EVERY_MONTH = 3, "Каждый месяц"


class NewsLetter(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя рассылки')
    time_mailing = models.TimeField(verbose_name='Время отправки')
    periodicity_mailing = models.IntegerField(choices=PeriodicityChoice.choices, default=PeriodicityChoice.EVERY_DAY, verbose_name='Периодичность')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Автор')

    def __str__(self):
        return f'{self.name} {self.time_mailing}'


class Message(models.Model):
    title = models.CharField(max_length=50, verbose_name='Title')
    body = models.TextField(verbose_name='Content')
    newsletter = models.ForeignKey(NewsLetter, on_delete=models.CASCADE)
    status_mailing = models.IntegerField(choices=StatusChoice.choices, default=StatusChoice.CREATED,
                                         verbose_name='Статус')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'


class Client(models.Model):
    email = models.EmailField(verbose_name='Email')
    full_name = models.CharField(max_length=255, verbose_name='Full Name')
    newsletter = models.ForeignKey(NewsLetter, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.full_name


class LogNewsLetter(models.Model):
    data_newsletter = models.DateTimeField(auto_now_add=True, verbose_name='Data Time Last Try')
    status_mailing = models.IntegerField(choices=StatusChoice.choices, default=StatusChoice.CREATED,
                                         verbose_name='Status')
    answer_server = models.TextField(verbose_name='Answer from Server')

main/forms.py
from django import forms

from main.models import NewsLetter, Message, Client


class NewsLetterForm(forms.ModelForm):

    class Meta:
        model = NewsLetter
        fields = ('name', 'time_mailing', 'periodicity_mailing')


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ('title', 'body')


class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ('email', 'full_name')

main/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from blog.models import Blog


from main.forms import NewsLetterForm, ClientForm, MessageForm
from main.models import NewsLetter, Client, Message, StatusChoice


class NewsLetterListView(ListView):
    model = NewsLetter
    template_name = "main/index.html"

    def get_context_data(self, **kwargs):
        """
        A method to retrieve and prepare the context data for the view, including counts and random articles.
        """
        context_data = super().get_context_data(**kwargs)
        count_mailing = NewsLetter.objects.count()
        active_mailing = Message.objects.filter(
            status_mailing=StatusChoice.PROCESSING
        ).count()
        count_unique_client = Client.objects.values("email").distinct().count()
        blog_articles = Blog.objects.all()
        articles = random.sample(list(blog_articles), min(3, len(blog_articles)))
        context_data["count_mailing"] = count_mailing
        context_data["active_mailing"] = active_mailing
        context_data["count_unique_client"] = count_unique_client
        context_data["articles"] = articles
        return context_data


class NewsLetterCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):

    model = NewsLetter
    form_class = NewsLetterForm
    permission_required = "main.add_newsletter"
    success_url = reverse_lazy("main:index")
    login_url = "/user"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    permission_required = "main.add_message"
    success_url = reverse_lazy("main:index")
    login_url = "/user"

    def form_valid(self, form):
        if self.request.user != NewsLetter.objects.get(id=self.kwargs.get("pk")).user:
            raise Http404
        self.object = form.save(commit=False)
        self.object.newsletter_id = self.kwargs.get("pk")
        self.object.save()
        return super().form_valid(form)


class NewsLetterDetailView(DetailView):
    model = NewsLetter
    template_name = "main/newsletter.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        messages = Message.objects.filter(newsletter=self.object)
        context_data["messages"] = messages
        return context_data


class MyNewsLetterListView(LoginRequiredMixin, ListView):
    model = NewsLetter
    template_name = "main/my_newsletter_list.html"
    login_url = "/user"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["object_list"] = NewsLetter.objects.filter(user=self.request.user)

        return context_data


class NewsLetterUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = NewsLetter
    form_class = NewsLetterForm
    permission_required = "main.change_newsletter"
    success_url = reverse_lazy("main:index")
    login_url = "/user"

    def form_valid(self, form):
        if self.request.user != NewsLetter.objects.get(id=self.kwargs.get("pk")).user:
            raise Http404

        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        if self.request.user != NewsLetter.objects.get(id=self.kwargs.get("pk")).user:
            raise Http404
        return super().get(request, *args, **kwargs)


class NewsLetterDeleteView(DeleteView):
    model = NewsLetter
    template_name = "main/newsletter_delete.html"
    success_url = reverse_lazy("main:index")
    login_url = "/user"

    def form_valid(self, form):
        """
        Check if the form is valid and raise Http404 if the requesting user is not the owner of the newsletter.
        """
        if self.request.user != NewsLetter.objects.get(id=self.kwargs.get("pk")).user:
            raise Http404

        return super().form_valid(form)


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("main:index")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.newsletter_id = self.kwargs.get("pk")
        self.object.save()
        return super().form_valid(form)

main/templates/main/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'main/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">EmailStore - это отличный вариант для рассылки вашей корреспонденции</p>
</div>

<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
    </div>
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            EmailStore
            <small class="d-block mb-5 text-muted">&copy; {% now 'Y' %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main/templates/main/client_form.html
{% extends 'main/base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Сохранить</button>
</form>

{% endblock %}

main/templates/main/form_redirect.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Вы не можете создать новую рассылку</div>
            <div class="card-body">
                <a class="p-2 btn btn-outline-primary" href="/">Вернуться на главную?</a>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %} {% block content %}

<div class="col-12">
  <div class="row text-center">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <table class="table">
            <tbody>
              <tr>
                <td>Количество рассылок всего</td>
                <td>{{ count_mailing }}</td>
              </tr>
              <tr>
                <td>Количество активных рассылок</td>
                <td>{{ active_mailing }}</td>
              </tr>
              <tr>
                <td>Уникальные клиенты</td>
                <td>{{ count_unique_client }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <ul>
            {% for article in articles %}
            <li>
              <strong>{{ article.title }}</strong> -
              {{article.body|truncatechars:100}}
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% for object in object_list %}
<div class="col-6">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
    </div>
    <div class="card-body">
      <a
        href="{% url 'main:client_create' object.pk %}"
        type="button"
        class="btn btn-lg btn-block btn-outline-primary"
        >Подписаться на рассылку</a
      >
      <a
        href="{% url 'main:newsletter_detail' object.pk %}"
        type="button"
        class="btn btn-lg btn-block btn-outline-primary"
        >Подробнее о рассылке</a
      >
    </div>
  </div>
</div>
{% endfor %} {% endblock %}

main/templates/main/message_form.html
{% extends 'main/base.html' %}
{% block content %}

<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">
                Добавление сообщения
            </h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>

{% endblock %}

main/templates/main/my_newsletter_list.html
{% extends 'main/base.html' %}
{% block content %}

{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
        </div>
        <div class="card-body">

                <a href="{% url 'main:message_create' object.pk %}" type="button" class="btn btn-lg btn-block btn-light">Добавить сообщение</a>
                <a href="{% url 'main:newsletter_update' object.pk %}" type="button" class="btn btn-lg btn-block btn-light">Изменить рассылку</a>
                <a href="{% url 'main:newsletter_delete' object.pk %}" type="button" class="btn btn-lg btn-block btn-light">Удалить рассылку</a>
                <a href="{% url 'main:newsletter_detail' object.pk %}" type="button" class="btn btn-lg btn-block btn-light">Подробнее о рассылке</a>
                <a href="{% url 'main:client_create' object.pk %}" type="button" class="btn btn-lg btn-block btn-light">Подписаться на рассылку</a>

        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

main/templates/main/newsletter.html
{% extends 'main/base.html' %}
{% block content %}

<h4 class="my-0 font-weight-normal">{{object.title}}</h4>
{% for message in messages %}
<p>{{ message.title }}</p>
<p>{{ message.body }}</p>
<hr/>
{% endfor %}
<a href="{% url 'main:client_create' object.pk %}" type="button" class="btn btn-lg btn-block btn-light">Подписаться на
    рассылку</a>


{% endblock %}

main/templates/main/newsletter_delete.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container text-center">

    <form method="post">
        {% csrf_token %}
        <p>Вы действительно хотите удалить рассылку?</p>
        <button type="submit" class="btn btn-outline-danger">Удалить</button>
        <a href="{% url 'main:index' %}" type="button" class="btn btn-lg btn-block btn-light">Вернуться</a>

    </form>

</div>
{% endblock %}

main/templates/main/newsletter_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">
                Добавление рассылки
            </h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>
{% endblock %}